---
- hosts: nodejs
  remote_user: root
  tasks:
  # Doing this as a separate task is a bit cumbersome... what I really want is Chef's `if` attribute.
  - name: see if nodejs is installable
    shell: yum info nodejs
    ignore_errors: yes
    register: nodejs_available_output
    become: true

  - name: prepare to install nodejs
    # Normally, it's a bad idea to curl and pipe directly into bash, but:
    # http://imgur.com/a/iOW5P
    # We may also be able to use the yum_repository task, but this is the 
    # recommended approach on the Nodejs site.
    shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
    when: nodejs_available_output.rc != 0
    become: true

  - name: install nodejs
    yum: name=nodejs
    become: true

  - name: install git
    yum: name=git
    become: true

  - name: deploy app
    # Checking out this repo on the remote node... INCEPTION!
    git: repo=https://github.com/NickHeiner/ansible-hacking.git dest=/srv/ansible-hacking
    become: true
    args:
      accept_hostkey: true

  - name: install app
    shell: npm install --production-only
    args:
      chdir: /srv/ansible-hacking/nodejs-app

  - name: launch app
    shell: npm run launch
    args:
      chdir: /srv/ansible-hacking/nodejs-app
